INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (1, '北海道地方', 'hokkaido');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (2, '東北地方', 'touhoku');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (3, '関東地方', 'kantou');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (4, '中部地方', 'chubu');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (5, '近畿地方', 'kinki');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (6, '中国地方', 'chugoku');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (7, '四国地方', 'shikoku');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (8, '九州地方', 'kyushu');

INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (1, '北海道', 'hokkaido', 1);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (2, '青森県', 'aomori', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (3, '岩手県', 'iwate', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (4, '宮城県', 'miyagi', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (5, '秋田県', 'akita', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (6, '山形県', 'yamagata', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (7, '福島県', 'fukushima', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (8, '茨城県', 'ibaraki', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (9, '栃木県', 'tochigi', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (10, '群馬県', 'gunma', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (11, '埼玉県', 'saitama', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (12, '千葉県', 'chiba', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (13, '東京都', 'tokyo', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (14, '神奈川県', 'kanagawa', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (15, '新潟県', 'niigata', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (16, '富山県', 'toyama', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (17, '石川県', 'ishikawa', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (18, '福井県', 'fukui', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (19, '山梨県', 'yamanashi', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (20, '長野県', 'nagano', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (21, '岐阜県', 'gifu', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (22, '静岡県', 'shizuoka', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (23, '愛知県', 'aichi', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (24, '三重県', 'mie', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (25, '滋賀県', 'shiga', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (26, '京都府', 'kyoto', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (27, '大阪府', 'osaka', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (28, '兵庫県', 'hyogo', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (29, '奈良県', 'nara', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (30, '和歌山県', 'wakayama', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (31, '鳥取県', 'tottori', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (32, '島根県', 'shimane', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (33, '岡山県', 'okayama', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (34, '広島県', 'hiroshima', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (35, '山口県', 'yamaguchi', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (36, '徳島県', 'tokushima', 7);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (37, '香川県', 'kagawa', 7);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (38, '愛媛県', 'ehime', 7);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (39, '高知県', 'kochi', 7);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (40, '福岡県', 'fukuoka', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (41, '佐賀県', 'saga', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (42, '長崎県', 'nagasaki', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (43, '熊本県', 'kumamoto', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (44, '大分県', 'oita', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (45, '宮崎県', 'miyazaki', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (46, '鹿児島県', 'kagoshima', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (47, '沖縄県', 'okinawa', 8);
