INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (1, '–kŠC“¹’n•û', 'hokkaido');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (2, '“Œ–k’n•û', 'touhoku');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (3, 'ŠÖ“Œ’n•û', 'kantou');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (4, '’†•”’n•û', 'chubu');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (5, '‹ß‹E’n•û', 'kinki');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (6, '’†‘’n•û', 'chugoku');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (7, 'l‘’n•û', 'shikoku');
INSERT INTO areas (area_code, area_name, area_name_ank) VALUES (8, '‹ãB’n•û', 'kyushu');

INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (1, '–kŠC“¹', 'hokkaido', 1);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (2, 'ÂXŒ§', 'aomori', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (3, 'ŠâèŒ§', 'iwate', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (4, '‹{éŒ§', 'miyagi', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (5, 'H“cŒ§', 'akita', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (6, 'RŒ`Œ§', 'yamagata', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (7, '•Ÿ“‡Œ§', 'fukushima', 2);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (8, 'ˆïéŒ§', 'ibaraki', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (9, '“È–ØŒ§', 'tochigi', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (10, 'ŒQ”nŒ§', 'gunma', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (11, 'é‹ÊŒ§', 'saitama', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (12, 'ç—tŒ§', 'chiba', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (13, '“Œ‹“s', 'tokyo', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (14, '_“ŞìŒ§', 'kanagawa', 3);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (15, 'VŠƒŒ§', 'niigata', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (16, '•xRŒ§', 'toyama', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (17, 'ÎìŒ§', 'ishikawa', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (18, '•ŸˆäŒ§', 'fukui', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (19, 'R—œŒ§', 'yamanashi', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (20, '’·–ìŒ§', 'nagano', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (21, 'Šò•ŒŒ§', 'gifu', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (22, 'Ã‰ªŒ§', 'shizuoka', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (23, 'ˆ¤’mŒ§', 'aichi', 4);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (24, 'OdŒ§', 'mie', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (25, ' ‰êŒ§', 'shiga', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (26, '‹“s•{', 'kyoto', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (27, '‘åã•{', 'osaka', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (28, '•ºŒÉŒ§', 'hyogo', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (29, '“Ş—ÇŒ§', 'nara', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (30, '˜a‰ÌRŒ§', 'wakayama', 5);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (31, '’¹æŒ§', 'tottori', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (32, '“‡ªŒ§', 'shimane', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (33, '‰ªRŒ§', 'okayama', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (34, 'L“‡Œ§', 'hiroshima', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (35, 'RŒûŒ§', 'yamaguchi', 6);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (36, '“¿“‡Œ§', 'tokushima', 7);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (37, 'ìŒ§', 'kagawa', 7);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (38, 'ˆ¤•QŒ§', 'ehime', 7);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (39, '‚’mŒ§', 'kochi', 7);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (40, '•Ÿ‰ªŒ§', 'fukuoka', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (41, '²‰êŒ§', 'saga', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (42, '’·èŒ§', 'nagasaki', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (43, 'ŒF–{Œ§', 'kumamoto', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (44, '‘å•ªŒ§', 'oita', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (45, '‹{èŒ§', 'miyazaki', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (46, '­™“‡Œ§', 'kagoshima', 8);
INSERT INTO prefectures (prefecture_code, prefecture_name, prefecture_name_ank, prefecture_area_code) VALUES (47, '‰«“êŒ§', 'okinawa', 8);
